### ISSUE TITLE
Mispelled parameter name prerelase -> prerelease

### ISSUE THREAD

**Issue by 3DHDSoft** [node4good/msvs-com-helper#2]
Mispelled parameter name prerelase -> prerelease at https://github.com/node4good/msvs-com-helper/blob/2d36e95b0b19c23e8c861d45eadf693d106e0ffe/vswhere_usability_wrapper.cmd#L19

**Comment by refack** [comment]
Thank you. This required a semver-major version bump.
Fixed in https://github.com/node4good/msvs-com-helper/commit/e36955738fc341f8f8eea944f780368e74bb9ca3
