### ISSUE TITLE
Mispelled variable name VSWHERE_WITH_PRERELASE -> VSWHERE_WITH_PRERELEASE

### ISSUE THREAD

**Issue by 3DHDSoft** [node4good/msvs-com-helper#3]
Mispelled variable name VSWHERE_WITH_PRERELASE -> VSWHERE_WITH_PREREL**E**ASE at https://github.com/node4good/msvs-com-helper/blob/2d36e95b0b19c23e8c861d45eadf693d106e0ffe/vswhere_usability_wrapper.cmd#L19

https://github.com/node4good/msvs-com-helper/blob/2d36e95b0b19c23e8c861d45eadf693d106e0ffe/vswhere_usability_wrapper.cmd#L20

**Comment by refack** [comment]
Fixed in https://github.com/node4good/msvs-com-helper/commit/e36955738fc341f8f8eea944f780368e74bb9ca3
